spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discountDb
    username: postgres
    password: nicat12345
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082


grpc:
  server:
    host: localhost
    port: 9091